In [1]:
import pandas as pd
import numpy as np

Import the CSV

In [18]:
data = pd.read_csv (r'C://Users//US02244//python_files//Rthermal//p1.csv')
data

    Current (A)  Voltage (V)  Optical power (W)  Wavelength (nm)
0           NaN          NaN                NaN              NaN
1           2.0         1.34               0.95           960.90
2           4.0         1.37               3.17           961.77
3           6.0         1.39               5.38           962.61
4           8.0         1.41               7.56           963.41
5          10.0         1.44               9.71           964.27
6          12.0         1.45              11.83           965.29
7          14.0         1.47              13.89           966.17
8          16.0         1.49              15.89           967.21
9          18.0         1.50              17.81           968.59
10         20.0         1.51              19.70           969.51
11         22.0         1.53              21.50           970.66
12         24.0         1.54              23.12           972.21
13         25.0         1.54              23.95           972.67

You create the column Waste Heat

In [20]:
data['WasteHeat_W'] = (data['Current (A)'] * data['Voltage (V)']) - data['Optical power (W)']
data

    Current (A)  Voltage (V)  Optical power (W)  Wavelength (nm)  WasteHeat_W
0           NaN          NaN                NaN              NaN          NaN
1           2.0         1.34               0.95           960.90         1.73
2           4.0         1.37               3.17           961.77         2.31
3           6.0         1.39               5.38           962.61         2.96
4           8.0         1.41               7.56           963.41         3.72
5          10.0         1.44               9.71           964.27         4.69
6          12.0         1.45              11.83           965.29         5.57
7          14.0         1.47              13.89           966.17         6.69
8          16.0         1.49              15.89           967.21         7.95
9          18.0         1.50              17.81           968.59         9.19
10         20.0         1.51              19.70           969.51        10.50
11         22.0         1.53              21.50           970.66        12.16
12         24.0         1.54              23.12           972.21        13.84
13         25.0         1.54              23.95           972.67        14.55

delete the first line

In [21]:
df = data.iloc[1: , :]
df

    Current (A)  Voltage (V)  Optical power (W)  Wavelength (nm)  WasteHeat_W
1           2.0         1.34               0.95           960.90         1.73
2           4.0         1.37               3.17           961.77         2.31
3           6.0         1.39               5.38           962.61         2.96
4           8.0         1.41               7.56           963.41         3.72
5          10.0         1.44               9.71           964.27         4.69
6          12.0         1.45              11.83           965.29         5.57
7          14.0         1.47              13.89           966.17         6.69
8          16.0         1.49              15.89           967.21         7.95
9          18.0         1.50              17.81           968.59         9.19
10         20.0         1.51              19.70           969.51        10.50
11         22.0         1.53              21.50           970.66        12.16
12         24.0         1.54              23.12           972.21        13.84
13         25.0         1.54              23.95           972.67        14.55

Find the values of intercept and Cold WL

In [22]:
y = df['Wavelength (nm)']
x = df['WasteHeat_W']
slope_intercept = np.polyfit(x,y,1)
intercept = slope_intercept[1]
ColdWL_cst = 0.344088810685303
#print(intercept, ColdWL_cst)

Create two columns for intercept and Cold WL

In [23]:
df.loc[:,'intercept'] = intercept
df.loc[:,'ColdWL_cst'] = ColdWL_cst
df

,Current (A),Voltage (V),Optical power (W),Wavelength (nm),WasteHeat_W,intercept,ColdWL_cst
1,2.0,1.34,0.95,960.90,1.73,959.943521,0.344089
2,4.0,1.37,3.17,961.77,2.31,959.943521,0.344089
3,6.0,1.39,5.38,962.61,2.96,959.943521,0.344089
4,8.0,1.41,7.56,963.41,3.72,959.943521,0.344089
5,10.0,1.44,9.71,964.27,4.69,959.943521,0.344089
6,12.0,1.45,11.83,965.29,5.57,959.943521,0.344089
7,14.0,1.47,13.89,966.17,6.69,959.943521,0.344089
8,16.0,1.49,15.89,967.21,7.95,959.943521,0.344089
9,18.0,1.50,17.81,968.59,9.19,959.943521,0.344089
10,20.0,1.51,19.70,969.51,10.50,959.943521,0.344089
11,22.0,1.53,21.50,970.66,12.16,959.943521,0.344089
12,24.0,1.54,23.12,972.21,13.84,959.943521,0.344089
13,25.0,1.54,23.95,972.67,14.55,959.943521,0.344089

Create the column Temperature Change

In [25]:
df.loc[:,'Temp_Change_C'] = ( df['Wavelength (nm)'] - df['intercept'] ) / df['ColdWL_cst'] 
df

,Current (A),Voltage (V),Optical power (W),Wavelength (nm),WasteHeat_W,intercept,ColdWL_cst,Temp_Change_C
1,2.0,1.34,0.95,960.90,1.73,959.943521,0.344089,2.779745
2,4.0,1.37,3.17,961.77,2.31,959.943521,0.344089,5.308162
3,6.0,1.39,5.38,962.61,2.96,959.943521,0.344089,7.749393
4,8.0,1.41,7.56,963.41,3.72,959.943521,0.344089,10.074374
5,10.0,1.44,9.71,964.27,4.69,959.943521,0.344089,12.573729
6,12.0,1.45,11.83,965.29,5.57,959.943521,0.344089,15.538080
7,14.0,1.47,13.89,966.17,6.69,959.943521,0.344089,18.095559
8,16.0,1.49,15.89,967.21,7.95,959.943521,0.344089,21.118034
9,18.0,1.50,17.81,968.59,9.19,959.943521,0.344089,25.128627
10,20.0,1.51,19.70,969.51,10.50,959.943521,0.344089,27.802355
11,22.0,1.53,21.50,970.66,12.16,959.943521,0.344089,31.144515
12,24.0,1.54,23.12,972.21,13.84,959.943521,0.344089,35.649166
13,25.0,1.54,23.95,972.67,14.55,959.943521,0.344089,36.986031

Find the Theremal resistance

In [26]:
y1 = df['Temp_Change_C']
x1 = df['WasteHeat_W']
slope_intercept_1 = np.polyfit(x1,y1,1)
Theramal_resistance = slope_intercept_1[0]

print('Theramal Resistance =', round(Theramal_resistance, 2) , ' degC / W')

Theramal Resistance = 2.61  degC / W